# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "node-terraform-up-and-running-state"
    dynamodb_table = "node-terraform-up-and-running-locks-table"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "eu-west-3"
  }
}
